// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEg5auUmGjddE4IByqAo0fjfRX7FBHVsM',
    appId: '1:262793312227:web:375fd22067428967a0d2d6',
    messagingSenderId: '262793312227',
    projectId: 'store-app-68de5',
    authDomain: 'store-app-68de5.firebaseapp.com',
    storageBucket: 'store-app-68de5.firebasestorage.app',
    measurementId: 'G-1R4MXT4V0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAnVc6zxGvUXiKKTBnWU53JAVXHlLXYt0',
    appId: '1:262793312227:android:fc802fa28d516b94a0d2d6',
    messagingSenderId: '262793312227',
    projectId: 'store-app-68de5',
    storageBucket: 'store-app-68de5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEg5auUmGjddE4IByqAo0fjfRX7FBHVsM',
    appId: '1:262793312227:web:7a78cbe41a508a45a0d2d6',
    messagingSenderId: '262793312227',
    projectId: 'store-app-68de5',
    authDomain: 'store-app-68de5.firebaseapp.com',
    storageBucket: 'store-app-68de5.firebasestorage.app',
    measurementId: 'G-TQYE4F1F91',
  );
}
